In [1]:
from sklearn.datasets import fetch_openml

In [3]:
mnist = fetch_openml('mnist_784', version=1, as_frame=False)

/usr/local/lib/python3.11/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [4]:
x, y = mnist['data'], mnist['target']

In [5]:
x_train, x_test, y_train, y_test = x[:60000], x[60000:], y[:60000], y[60000:]

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
forest_clf = RandomForestClassifier(random_state=42)

In [8]:
forest_clf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [9]:
some_data = x[0]

In [10]:
forest_clf.predict([some_data])

array(['5'], dtype=object)

In [12]:
import numpy as np
y_train = y_train.astype(np.uint8)
y_test = y_test.astype(np.uint8)

In [13]:
from sklearn.linear_model import SGDClassifier

In [14]:
sgd_clf = SGDClassifier(random_state=42)

In [15]:
sgd_clf.fit(x_train, y_train)

SGDClassifier(random_state=42)

In [16]:
sgd_clf.predict([some_data])

array([3], dtype=uint8)

In [18]:
from sklearn.multiclass import OneVsOneClassifier

In [20]:
ovo_clf = OneVsOneClassifier(SGDClassifier(random_state=42))

In [21]:
ovo_clf.fit(x_train, y_train)

OneVsOneClassifier(estimator=SGDClassifier(random_state=42))

In [22]:
ovo_clf.predict([some_data])

array([5], dtype=uint8)

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
from sklearn.model_selection import cross_val_predict

In [25]:
cross_val_score(ovo_clf, x_train, y_train, cv=3, scoring='accuracy')

array([0.91545, 0.9131 , 0.92045])

In [26]:
cross_val_score(sgd_clf, x_train, y_train, cv=3, scoring='accuracy')

array([0.87365, 0.85835, 0.8689 ])

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()

In [30]:
transformed_x_train = scaler.fit_transform(x_train.astype(np.float64))

In [31]:
cross_val_score(ovo_clf, transformed_x_train, y_train, cv=3, scoring='accuracy')

array([0.91595, 0.9149 , 0.91845])

In [32]:
cross_val_score(sgd_clf, transformed_x_train, y_train, cv=3, scoring='accuracy')

array([0.8983, 0.891 , 0.9018])